import paramiko
c=paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("47.82.103.247",username="root",password="ROOT_PASSWORD_CHANGED_20260615",timeout=10,look_for_keys=False,allow_agent=False)
s=c.open_sftp()
s.put("f:/ClaudeFiles/_research/tools/email.html","/tmp/email.html")
s.put("f:/ClaudeFiles/_research/tools/translate.html","/tmp/translate.html")
s.close()
stdin,stdout,stderr=c.exec_command("mkdir -p /app/static/tools && mv /tmp/email.html /app/static/tools/email.html && mv /tmp/translate.html /app/static/tools/translate.html && echo done")
o=stdout.read().decode(errors='replace')
print(o)
stdin,stdout,stderr=c.exec_command("curl -sk -o /dev/null -w '%{http_code}' https://tokenline.top/tools/email.html")
print("email:",stdout.read().decode())
stdin,stdout,stderr=c.exec_command("curl -sk -o /dev/null -w '%{http_code}' https://tokenline.top/tools/translate.html")
print("translate:",stdout.read().decode())
stdin,stdout,stderr=c.exec_command("curl -sk -o /dev/null -w '%{http_code}' https://tokenline.top/")
print("index:",stdout.read().decode())
c.close()
